import mongoose from "mongoose";
import dotenv from "dotenv";
import productModel from "./models/productModel.js";
import categoryModel from "./models/categoryModel.js";
import brandModel from "./models/brandModel.js";

dotenv.config();

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB for Seeding...");

    // Lookup Category and Brand IDs dynamically
    const catsArr = await categoryModel.find({});
    const brandsArr = await brandModel.find({});

    const findCat = (name) => catsArr.find(c => c.name === name)?._id;
    const findBrand = (name) => brandsArr.find(b => b.name === name)?._id;

    const laptops = [
      // APPLE
      {
        name: "Apple MacBook Pro M3 Max",
        slug: "apple-macbook-pro-m3-max-14",
        brand: findBrand("Apple"),
        category: findCat("Premium Laptops"),
        series: "MacBook Pro",
        price: 349900,
        originalPrice: 359000,
        shortDescription: "Extreme performance for the most demanding workflows.",
        description: "The M3 Max chip drives extreme performance for demanding workflows. Featuring a 14-core CPU and 30-core GPU, this machine is built for professionals who need the absolute best.",
        processor: "Apple M3 Max (14-core CPU)",
        ram: "36GB Unified Memory",
        storage: "1TB Ultra-fast SSD",
        storageType: "SSD",
        displaySize: "14.2-inch",
        resolution: "3024 x 1964 (Liquid Retina XDR)",
        display: "120Hz ProMotion, 1600 nits peak brightness",
        graphics: "30-core Apple GPU",
        operatingSystem: "macOS Sonoma",
        battery: "72.4Whr (Up to 18 hours)",
        weight: "1.62 kg",
        color: "Space Black",
        warranty: "1 Year Apple Care Support",
        stock: 12,
        sku: "MBP-M3MAX-BLK",
        condition: "New",
        featured: true,
        bestseller: true,
        trending: true,
        image: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // HP
      {
        name: "HP Omen Transversal 16",
        slug: "hp-omen-16-gaming",
        brand: findBrand("HP"),
        category: findCat("Gaming Laptops"),
        series: "Omen",
        price: 145000,
        originalPrice: 165000,
        shortDescription: "High-octane gaming with advanced cooling.",
        description: "Dominate the competition with the Omen 16. Powered by an Intel i7-13700HX and RTX 4060, it stays cool under pressure with Omen Tempest Cooling.",
        processor: "Intel Core i7-13700HX (16 Cores)",
        ram: "16GB DDR5 4800MHz",
        storage: "1TB NVMe Gen4 SSD",
        storageType: "SSD",
        displaySize: "16.1-inch",
        resolution: "2560 x 1440 (QHD)",
        display: "165Hz, 3ms, 100% sRGB",
        graphics: "NVIDIA RTX 4060 8GB GDDR6",
        operatingSystem: "Windows 11 Home",
        battery: "83Whr (Fast Charge Support)",
        weight: "2.35 kg",
        color: "Shadow Black",
        warranty: "2 Years Onsite Warranty",
        stock: 25,
        sku: "HP-OMEN-16-01",
        condition: "New",
        featured: true,
        bestseller: false,
        trending: true,
        image: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // DELL
      {
        name: "Dell Alienware m18 R1",
        slug: "dell-alienware-m18-r1-rtx-4080",
        brand: findBrand("Dell"),
        category: findCat("Gaming Laptops"),
        series: "Alienware",
        price: 289000,
        originalPrice: 320000,
        shortDescription: "Maximum screen size. Absolute power.",
        description: "The Alienware m18 is our most powerful laptop ever. It features a massive 18-inch display and the latest hardware for a desktop-replacement experience.",
        processor: "Intel Core i9-13980HX",
        ram: "32GB (2x16GB) DDR5 4800MHz",
        storage: "2TB RAID 0 (2x1TB) SSD",
        storageType: "SSD",
        displaySize: "18.0-inch",
        resolution: "1920 x 1200 (FHD+)",
        display: "480Hz Refresh Rate, 3ms",
        graphics: "NVIDIA RTX 4080 12GB GDDR6",
        operatingSystem: "Windows 11 Pro",
        battery: "97Whr Extreme Capacity",
        weight: "4.04 kg",
        color: "Dark Metallic Moon",
        warranty: "1 Year Premium Support Plus",
        stock: 8,
        sku: "AW-M18-02",
        condition: "New",
        featured: true,
        bestseller: false,
        trending: true,
        image: ["https://images.unsplash.com/photo-1544244015-0cd4b3ffc6b0?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // LENOVO
      {
        name: "Lenovo Yoga 7i Gen 8",
        slug: "lenovo-yoga-7i-gen-8-evo",
        brand: findBrand("Lenovo"),
        category: findCat("Student Laptops"),
        series: "Yoga",
        price: 92000,
        originalPrice: 110000,
        shortDescription: "Versatile 2-in-1 for students and professionals.",
        description: "Design and perform with the versatile 360-degree hinge on the Yoga 7i. Intel Evo platform ensures battery life and responsiveness.",
        processor: "Intel Core i7-1355U (Evo)",
        ram: "16GB LPDDR5 5200MHz",
        storage: "512GB PCIe 4.0 SSD",
        storageType: "SSD",
        displaySize: "14-inch",
        resolution: "2240 x 1400 (2.2K)",
        display: "Multi-touch, IPS, 300 nits, Dolby Vision",
        graphics: "Intel Iris Xe Graphics",
        operatingSystem: "Windows 11 Home",
        battery: "71Whr (Up to 14 hours)",
        weight: "1.55 kg",
        color: "Storm Grey",
        warranty: "1 Year ADP + Premium Care",
        stock: 40,
        sku: "LEN-YOGA7-01",
        condition: "New",
        featured: false,
        bestseller: true,
        trending: false,
        image: ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // ASUS
      {
        name: "ASUS Vivobook Go 15",
        slug: "asus-vivobook-go-15-budget",
        brand: findBrand("ASUS"),
        category: findCat("Budget Laptops"),
        series: "Vivobook",
        price: 35000,
        originalPrice: 48000,
        shortDescription: "Lightweight and efficient budget workhorse.",
        description: "Get through your daily tasks effortlessly with the ASUS Vivobook Go 15. Slim design and long battery life.",
        processor: "AMD Ryzen 3 7320U",
        ram: "8GB LPDDR5",
        storage: "512GB NVMe SSD",
        storageType: "SSD",
        displaySize: "15.6-inch",
        resolution: "1920 x 1080 (FHD)",
        display: "Anti-glare, slim bezel",
        graphics: "AMD Radeon Graphics",
        operatingSystem: "Windows 11 Home S Mode",
        battery: "42Whr 3-cell",
        weight: "1.63 kg",
        color: "Mixed Black",
        warranty: "1 Year Global Warranty",
        stock: 100,
        sku: "AS-VB-GO15-01",
        condition: "New",
        featured: false,
        bestseller: true,
        trending: true,
        image: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // ACER
      {
        name: "Acer Swift Edge 16",
        slug: "acer-swift-edge-16-oled",
        brand: findBrand("Acer"),
        category: findCat("Premium Laptops"),
        series: "Swift",
        price: 115000,
        originalPrice: 135000,
        shortDescription: "The world's lightest 16-inch OLED laptop.",
        description: "Experience stunning visuals on the 4K OLED display. Ultra-lightweight magnesium-aluminum alloy chassis for extreme portability.",
        processor: "AMD Ryzen 7 7840U",
        ram: "16GB LPDDR5",
        storage: "1TB NVMe SSD",
        storageType: "SSD",
        displaySize: "16.0-inch",
        resolution: "3840 x 2400 (4K OLED)",
        display: "HDR True Black 500, 100% DCI-P3",
        graphics: "AMD Radeon 780M Graphics",
        operatingSystem: "Windows 11 Home",
        battery: "54Whr Fast Charging",
        weight: "1.17 kg",
        color: "Olivine Black",
        warranty: "1 Year Carry-in Warranty",
        stock: 15,
        sku: "AC-SWE-16",
        condition: "New",
        featured: true,
        bestseller: false,
        trending: false,
        image: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // MSI
      {
        name: "MSI Katana 15 B13V",
        slug: "msi-katana-15-rtx-4050",
        brand: findBrand("MSI"),
        category: findCat("Gaming Laptops"),
        series: "Katana",
        price: 105000,
        originalPrice: 125000,
        shortDescription: "Sharp performance for every gamer.",
        description: "Sharpen your game. The Katana 15 features the latest 13th Gen Intel core processors and RTX 40 series graphics for smooth high-fps gaming.",
        processor: "Intel Core i7-13620H",
        ram: "16GB DDR5 5200MHz",
        storage: "1TB NVMe SSD",
        storageType: "SSD",
        displaySize: "15.6-inch",
        resolution: "1920 x 1080 (FHD)",
        display: "144Hz IPS-Level, 45% NTSC",
        graphics: "NVIDIA RTX 4050 6GB GDDR6",
        operatingSystem: "Windows 11 Home",
        battery: "53.5Whr 3-cell",
        weight: "2.25 kg",
        color: "Core Black",
        warranty: "2 Years Carry-in Warranty",
        stock: 20,
        sku: "MSI-KAT-15",
        condition: "New",
        featured: false,
        bestseller: true,
        trending: true,
        image: ["https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // Dell Business
      {
        name: "Dell Latitude 7440",
        slug: "dell-latitude-7440-business",
        brand: findBrand("Dell"),
        category: findCat("Business Laptops"),
        series: "Latitude",
        price: 155000,
        originalPrice: 175000,
        shortDescription: "Secure and lightweight business elite.",
        description: "World's smallest 14-inch premium commercial laptop. Featuring intelligent privacy, collaboration and connectivity features.",
        processor: "Intel Core i5-1345U (vPro)",
        ram: "16GB LPDDR5 (Soldered)",
        storage: "512GB NVMe SSD",
        storageType: "SSD",
        displaySize: "14.0-inch",
        resolution: "1920 x 1200 (FHD+)",
        display: "ComfortView Plus, Anti-glare",
        graphics: "Intel Iris Xe Graphics",
        operatingSystem: "Windows 11 Pro",
        battery: "57Whr ExpressCharge",
        weight: "1.33 kg",
        color: "Titan Gray",
        warranty: "3 Years ProSupport Onsite",
        stock: 30,
        sku: "DL-LAT74-01",
        condition: "New",
        featured: false,
        bestseller: false,
        trending: false,
        image: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // HP Business
      {
        name: "HP EliteBook 840 G10",
        slug: "hp-elitebook-840-g10-pro",
        brand: findBrand("HP"),
        category: findCat("Business Laptops"),
        series: "EliteBook",
        price: 148000,
        originalPrice: 162000,
        shortDescription: "Premium collaboration for enterprise.",
        description: "Optimized for hybrid work. The EliteBook features 5MP camera and high-performance collaboration tools for professional results.",
        processor: "Intel Core i7-1355U",
        ram: "16GB (1x16GB) DDR5",
        storage: "1TB NVMe SSD",
        storageType: "SSD",
        displaySize: "14.0-inch",
        resolution: "1920 x 1200 (WUXGA)",
        display: "400 nits, 100% sRGB, IPS",
        graphics: "Intel Iris Xe Graphics",
        operatingSystem: "Windows 11 Pro",
        battery: "51Whr Long Life",
        weight: "1.36 kg",
        color: "Silver",
        warranty: "3 Years Next Business Day Onsite",
        stock: 22,
        sku: "HP-EB840-G10",
        condition: "New",
        featured: false,
        bestseller: false,
        trending: false,
        image: ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // MSI Creator
      {
        name: "MSI Creator M16",
        slug: "msi-creator-m16-a12u",
        brand: findBrand("MSI"),
        category: findCat("Creator Laptops"),
        series: "Creator",
        price: 125000,
        originalPrice: 145000,
        shortDescription: "Tech meets Aesthetics for visual artists.",
        description: "Visualized with the Golden Ratio. The 16:10 display provides extra workspace for artists and designers using creative suites.",
        processor: "Intel Core i7-12700H",
        ram: "16GB DDR4",
        storage: "512GB NVMe SSD",
        storageType: "SSD",
        displaySize: "16.0-inch",
        resolution: "2560 x 1600 (QHD+)",
        display: "60Hz, 100% DCI-P3 (Typical)",
        graphics: "NVIDIA RTX 3050 Ti 4GB",
        operatingSystem: "Windows 11 Home",
        battery: "53Whr 3-cell",
        weight: "2.26 kg",
        color: "Black",
        warranty: "1 Year Global Warranty",
        stock: 12,
        sku: "MSI-CRM16-01",
        condition: "New",
        featured: true,
        bestseller: false,
        trending: true,
        image: ["https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // ASUS Creator
      {
        name: "ASUS Zenbook Pro 14 OLED",
        slug: "asus-zenbook-pro-14-oled-creator",
        brand: findBrand("ASUS"),
        category: findCat("Creator Laptops"),
        series: "Zenbook",
        price: 185000,
        originalPrice: 210000,
        shortDescription: "Unleash your creative power with ASUS Dial.",
        description: "Featuring the unique ASUS Dial for precise creative control. The 2.8K OLED display ensures color perfection for every pixel.",
        processor: "Intel Core i9-13900H",
        ram: "32GB DDR5 (Soldered)",
        storage: "1TB NVMe Gen4 SSD",
        storageType: "SSD",
        displaySize: "14.5-inch",
        resolution: "2880 x 1800 (2.8K OLED)",
        display: "120Hz, 550 nits, Pantone Validated",
        graphics: "NVIDIA RTX 4060 8GB",
        operatingSystem: "Windows 11 Home",
        battery: "76Whr High Capacity",
        weight: "1.65 kg",
        color: "Tech Black",
        warranty: "2 Years Premium Support",
        stock: 10,
        sku: "AS-ZBPRO-14",
        condition: "New",
        featured: true,
        bestseller: true,
        trending: true,
        image: ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // Apple Air
      {
        name: "Apple MacBook Air 13 (M2)",
        slug: "apple-macbook-air-m2-midnight",
        brand: findBrand("Apple"),
        category: findCat("Student Laptops"),
        series: "MacBook Air",
        price: 99900,
        originalPrice: 114900,
        shortDescription: "Strikingly thin. All day battery.",
        description: "Redesigned for M2 chip. Insanely thin and fast, the MacBook Air is perfect for students who need power and portability without a fan.",
        processor: "Apple M2 (8-core CPU)",
        ram: "8GB Unified Memory",
        storage: "256GB SSD",
        storageType: "SSD",
        displaySize: "13.6-inch",
        resolution: "2560 x 1664 (Liquid Retina)",
        display: "500 nits, P3 Wide Color",
        graphics: "8-core Apple GPU",
        operatingSystem: "macOS Sonoma",
        battery: "52.6Whr (Up to 18 hours)",
        weight: "1.24 kg",
        color: "Midnight",
        warranty: "1 Year Official Warranty",
        stock: 50,
        sku: "AIR-M2-MDN",
        condition: "New",
        featured: false,
        bestseller: true,
        trending: true,
        image: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // Acer Gaming
      {
        name: "Acer Nitro V 15",
        slug: "acer-nitro-v-15-rtx-4050",
        brand: findBrand("Acer"),
        category: findCat("Gaming Laptops"),
        series: "Nitro",
        price: 78000,
        originalPrice: 99000,
        shortDescription: "Best value for mid-range gaming.",
        description: "Unleash your gaming potential. The Nitro V 15 combines a fast CPU and GPU for an immersive gaming experience without breaking the bank.",
        processor: "Intel Core i5-13420H",
        ram: "16GB DDR5",
        storage: "512GB NVMe SSD",
        storageType: "SSD",
        displaySize: "15.6-inch",
        resolution: "1920 x 1080 (FHD)",
        display: "144Hz, IPS, 3ms Response",
        graphics: "NVIDIA RTX 4050 6GB",
        operatingSystem: "Windows 11 Home",
        battery: "57Whr 3-cell",
        weight: "2.1 kg",
        color: "Obsidian Black",
        warranty: "1 Year International",
        stock: 35,
        sku: "AC-NV-15",
        condition: "New",
        featured: false,
        bestseller: true,
        trending: false,
        image: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // Lenovo Business
      {
        name: "Lenovo ThinkPad X1 Carbon Gen 11",
        slug: "lenovo-thinkpad-x1-carbon-gen-11",
        brand: findBrand("Lenovo"),
        category: findCat("Business Laptops"),
        series: "ThinkPad",
        price: 215000,
        originalPrice: 245000,
        shortDescription: "The gold standard for business portability.",
        description: "Ultralight, ultrapowerful. X1 Carbon is the ultimate business tool, featuring military-grade durability and world-class security.",
        processor: "Intel Core i7-1365U (vPro)",
        ram: "32GB LPDDR5 6000MHz",
        storage: "1TB PCIe 4.0 SSD",
        storageType: "SSD",
        displaySize: "14.0-inch",
        resolution: "2880 x 1800 (2.8K OLED)",
        display: "400 nits, Dolby Vision, Anti-glare",
        graphics: "Intel Iris Xe Graphics",
        operatingSystem: "Windows 11 Pro",
        battery: "57Whr Fast Charging",
        weight: "1.12 kg",
        color: "Deep Black",
        warranty: "3 Years Premier Support",
        stock: 15,
        sku: "LEN-X1C-11",
        condition: "New",
        featured: true,
        bestseller: false,
        trending: false,
        image: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      },
      // HP Budget
      {
        name: "HP Laptop 15s",
        slug: "hp-laptop-15s-ryzen-3",
        brand: findBrand("HP"),
        category: findCat("Budget Laptops"),
        series: "15s",
        price: 32000,
        originalPrice: 42000,
        shortDescription: "Ideal for light office work and web browsing.",
        description: "Reliable performance for every day. With a long battery life and micro-edge bezel, it's perfect for all your daily computing needs.",
        processor: "AMD Ryzen 3 5300U",
        ram: "8GB DDR4 3200MHz",
        storage: "512GB NVMe SSD",
        storageType: "SSD",
        displaySize: "15.6-inch",
        resolution: "1920 x 1080 (FHD)",
        display: "Anti-glare, slim bezel",
        graphics: "AMD Radeon Graphics",
        operatingSystem: "Windows 11 Home",
        battery: "41Whr 3-cell",
        weight: "1.69 kg",
        color: "Natural Silver",
        warranty: "1 Year Onsite Warranty",
        stock: 75,
        sku: "HP-15S-01",
        condition: "New",
        featured: false,
        bestseller: true,
        trending: false,
        image: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800"],
        date: Date.now()
      }
    ];

    // Remove existing products to avoid duplicates during conversion testing
    await productModel.deleteMany({});
    console.log("Cleared existing products.");

    await productModel.insertMany(laptops);
    console.log(`${laptops.length} Laptops Seeded Successfully!`);

    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

seedDB();
